title: "Lateef Adeleke"
description: "Researcher in Linguistics • Language Documentation • NLP for low-resource languages"
url: "https://ladeleke.github.io"
theme: jekyll-theme-cayman   # simple built-in theme
markdown: kramdown
plugins:
  - jekyll-seo-tag
