title: "Lateef Adeleke"
description: "Language Documentation and Description â€¢ NLP for low-resource languages"
url: "https://lateefadeleke.github.io"
theme: jekyll-theme-cayman   # simple built-in theme
markdown: kramdown
markdown: ![Profile photo](/assets/img/IMG_4798.JPG)
plugins:
  - jekyll-seo-tag
