title: "Lateef Adeleke"
description: "Language Documentation and Description â€¢ NLP for low-resource languages"
url: "https://lateefadeleke.github.io"
theme: jekyll-theme-cayman   # simple built-in theme
markdown: kramdown
plugins:
  - jekyll-seo-tag
