title: "Lateef Adeleke"
description: "Researcher in Linguistics • Language Documentation • NLP for low-resource languages"
url: "https://lateefadeleke.github.io"
theme: jekyll-theme-cayman
markdown: kramdown
plugins:
  - jekyll-seo-tag
